### ISSUE TITLE
Trsanction.Sign(ISecret, bool) is obsolete

### ISSUE THREAD

**Issue by JayricMok** [ProgrammingBlockchain/ProgrammingBlockchain#112]
I am new and I try to follow this tutorial https://www.youtube.com/watch?v=X4ZwRWIF49w, but facing an issue about `Trsanction.Sign(ISecret, bool) is obsolete` , it say use `Trsanction.Sign(ISecret, ICoin[] instead)`.

            var secret = new BitcoinSecret("thekey");
            var privateKey = secret.PrivateKey;

            Transaction tx = new Transaction();
            var input = new TxIn();
            input.PrevOut = new OutPoint(new uint256("thetransaction"), 1);
            input.ScriptSig = secret.GetAddress().ScriptPubKey;
            tx.AddInput(input);

            TxOut output = new TxOut();
            var destination = BitcoinAddress.Create("thereceiveraddress", Network.TestNet);
            Money fee = Money.Satoshis(1000);
            output.Value = Money.Coins(0.275m) - fee;
            output.ScriptPubKey = destination.ScriptPubKey;
            tx.AddOutput(output);
            tx.Sign(secret, false);

**Comment by NicolasDorier** [comment]
Read the book and use TransactionBuilder instead.

**Comment by JayricMok** [comment]
@NicolasDorier I read the book until https://programmingblockchain.gitbooks.io/programmingblockchain/content/bitcoin_transfer/spend_your_coin.html and follow the script `transaction.Sign(bitcoinPrivateKey, false);` and say `Trsanction.Sign(ISecret, bool) is obsolete` . Can you tell me why jump to `TransactionBuilder `

**Comment by NicolasDorier** [comment]
Ignore this obsolete message for the sake of learning. When you lean more about Bitcoin, the book explain how to use TransactionBuilder and why it is better.

**Comment by timothyparez** [comment]
I recently started reading this book and was following along with the samples,  
I ended up running into the same issue as @JayricMok.  

Perhaps it might be a good idea to add a note there to let the reader know that,
for the sake of learning, it is ok to ignore the `method is obsolete` warning at this point
and that a better alternative will be discussed later on in the book.

**Comment by NicolasDorier** [comment]
Sadly I can't add a note on youtube :(

**Comment by timothyparez** [comment]
What video?

**Comment by NicolasDorier** [comment]
https://www.youtube.com/watch?v=X4ZwRWIF49w

**Comment by timothyparez** [comment]
Maybe you can update the video description. But anyway, I added the note to the page.

**Comment by timothyparez** [comment]
I think so yes :)
