### ISSUE TITLE
About example code of section 1.2.4 Transaction 

### ISSUE THREAD

**Issue by TKaiC666** [ProgrammingBlockchain/ProgrammingBlockchain#113]
Content of TxOut has following example code :
<pre><code>
Money twentyOneBtc = new Money(21, MoneyUnit.BTC);
var scriptPubKey = transaction.Outputs.First().ScriptPubKey;
TxOut txOut = new TxOut(twentyOneBtc, scriptPubKey);
</code></pre>
But I can't find transaction.Outputs.First() function,how can I slove this problem?

**Comment by nopara73** [comment]
Add linq namespace.

**Comment by TKaiC666** [comment]
@nopara73 It's work! thank you!
