### ISSUE TITLE
explicitely set transaction fees are not being honored by the network

### ISSUE THREAD

**Issue by gked** [ProgrammingBlockchain/ProgrammingBlockchain#114]
Hi,
I apologize ahead of time if this is the wrong place to ask questions about this type of problems while reading the book.

I have basically wrote some code that transferred portion of BTC from one of my addresses into my other address.

I moved the money from  address **xxxxxxx....** let's call it source into address **yyyyyyy...**, let's call it target.

Source had 0.00734402.

I wrote some code to transfer .002 bitcoin into the target with explicitly setting transaction fee to be 200 Satoshis and then published it through one of the publicly available nodes.

To my surprise, it didn't honor the request it basically used up everything (0.00734402 - .002 = 534602 Satoshis) in fees.

Does anyone know why this happened?

My code below:
```
           Transaction tx = Transaction.Create(network);

            // from where are the money is sent 
            var input = new TxIn();
            input.PrevOut = new OutPoint(new uint256("zzzz"), 0);
            input.ScriptSig =  secret.GetAddress().ScriptPubKey; // get the ScriptPubKey of the sender
            tx.AddInput(input);

            // where the money are being sent to
            TxOut output = new TxOut();
            var destination = BitcoinAddress.Create("yyyyy");
            Money fee = Money.Satoshis(200);
            output.Value = Money.Coins(0.002m) - fee;
            output.ScriptPubKey = destination.ScriptPubKey;
            tx.AddOutput(output);

            tx.Sign(secret, false);

            //let's broadcast the transaction now
            var node = Node.Connect(network, "88.99.191.100:8333");
            node.VersionHandshake();
            node.SendMessage(new InvPayload(tx));
            node.SendMessage(new TxPayload(tx));
            Thread.Sleep(4000);
            node.Disconnect();
```

**Comment by gked** [comment]
OK, looks like i didn't read the chapter far enough. I see that I had to explicitly send the change back to my address if I wanted the keep it. Argh!!!
Then there's another question. If I dont explicitely specify the change to be sent back to the address does it then mean that it will automatically be sent to the miner in addition to the miner free I specified originally? This seems wrong. Instead, the transaction should not succeed in this case.

**Comment by NicolasDorier** [comment]
> If I dont explicitely specify the change to be sent back to the address does it then mean that it will automatically be sent to the miner in addition to the miner free I specified originally? This seems wrong. Instead, the transaction should not succeed in this case.

Yes, it would send to the miner. Nothing I can do about it, this is Bitcoin's rule.
Use `TransactoinBuilder` explained later in the book instead of manually creating transactions. It prevents foot shooting.

**Comment by gked** [comment]
@NicolasDorier thank you for the clarification. Perhaps, it is worth making a note of this in the book so people don't make the same mistake. In any case, I am closing the issue as resolved.

**Comment by NicolasDorier** [comment]
Please, make a pull request in the book to make it more clear.
