### ISSUE TITLE
cannot convert from 'NBitcoin.BitcoinSecret' to 'System.Collections.Generic.IEnumerable<NBitcoin.BitcoinSecret>' 

### ISSUE THREAD

**Issue by nharmon9** [ProgrammingBlockchain/ProgrammingBlockchain#134]
In Spend Your Coins when signing the transaction.

**Comment by nopara73** [comment]
`new []{secret}`

**Comment by nharmon9** [comment]
Changing this:
`transaction.Sign( bitcoinPrivateKey, receivedCoins.ToArray());`
To this worked for me:
`transaction.Sign(new[] { bitcoinPrivateKey }, receivedCoins.ToArray());`
Thank you!

**Comment by nopara73** [comment]
Your welcome. I made a PR to NBitcoin, so your previous method to work in the future without arraying the coins. https://github.com/MetacoSA/NBitcoin/pull/780
