### ISSUE TITLE
PublicKeyHash & GetAddress (Bitcoin address)

### ISSUE THREAD

**Issue by leshik** [ProgrammingBlockchain/ProgrammingBlockchain#136]
Shouldn't `GetAddress` be called on `PublicKey` (and not `PublicKeyHash`)? The way it is now doesn't work for me.

![image](https://user-images.githubusercontent.com/443678/77242227-e422c200-6c2e-11ea-9101-723ff17dd14c.png)

Same in the ScriptPubKey section (not sure how it can be fixed):

![image](https://user-images.githubusercontent.com/443678/77242579-7bd5df80-6c32-11ea-8a24-9f50e0c0f621.png)

Sorry if these are dumb questions, novice here.

**Comment by leshik** [comment]
Figured it out, it seems `GetAddress` should have one argument when called on `publicKeyHash`, which is the network, i.e. `var mainNetAddress = publicKeyHash.GetAddress(Network.Main)`. Is this correct?

**Comment by nopara73** [comment]
Not sure, there's a huge legacy mess here. We do it from pubkey, you can't go wrong with this: `(BitcoinPubKeyAddress)PubKey.GetAddress(ScriptPubKeyType.Legacy, network);`

Scripts:

https://github.com/zkSNACKs/WalletWasabi/blob/87fc50253861362c081353e42246ee54727b817d/WalletWasabi/Blockchain/Keys/HdPubKey.cs#L21-L24

Addresses:

https://github.com/zkSNACKs/WalletWasabi/blob/87fc50253861362c081353e42246ee54727b817d/WalletWasabi/Blockchain/Keys/HdPubKey.cs#L101-L105

**Comment by NicolasDorier** [comment]
```csharp
pubkey.Hash.GetAddress(Network.Main) == pubkey.GetAddress(ScriptPubKeyType.Legacy, Network.Main)
```
