### ISSUE TITLE
Can I convert the address from 1** to 3** or bc1*** without a private key?

### ISSUE THREAD

**Issue by shawenbin** [ProgrammingBlockchain/ProgrammingBlockchain#150]
eg:

1QFWLqCzG1ATEXfCoNwctyBa4LbD2YKGPu => 3KTi5wBeC76JGbrzzRAtUQg3tX3oTGGBdZ
3KTi5wBeC76JGbrzzRAtUQg3tX3oTGGBdZ => bc1qluyntw6a73qlste7w5hc9tpfawzct36ghu7agc

**Comment by adamPetho** [comment]
No, and please don't try to fiddle with the addresses.

> As a sender, you shouldn't care about what type of address the receiver gives you, and certainly not try to guess how you can modify it.

> As a receiver, if you want to give out a P2SH (3**) address (presumably because you want multisig security or segwit?), just upgrade your wallet so that supports the feature and create a new address.

Here is the whole answer (Note: p2pkh = 1**, p2sh = 3**, Bech32 = bc1***):
https://bitcoin.stackexchange.com/a/72776
