### ISSUE TITLE
"Spend Your Coin" Invalid Syntax

### ISSUE THREAD

**Issue by GravlLift** [ProgrammingBlockchain/ProgrammingBlockchain#155]
Looks like the section [From Where](https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/blob/70eafacbe8cba5ca90e798c98fb0472a3b0a90c3/bitcoin_transfer/spend_your_coin.md#from-where) contains some invalid code. Specifically, `bitcoinPrivateKey.ScriptPubKey` on line 60 in this code snippet. 

https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/blob/70eafacbe8cba5ca90e798c98fb0472a3b0a90c3/bitcoin_transfer/spend_your_coin.md#L56-L67

`bitcoinPrivateKey` is a variable of type `BitcoinSecret`. `ScriptPubKey` is implemented explicitly from interface `IDestination`, so I think the code needs to cast `bitcoinPrivateKey` to that interface at some point to get this code to compile?

**Comment by yahiheb** [comment]
![Capture](https://user-images.githubusercontent.com/52379387/130138504-d0150b52-2b25-4617-bb39-c30268be72a6.PNG)

Replace that line with 
`if (coin.TxOut.ScriptPubKey == bitcoinPrivateKey.GetAddress(ScriptPubKeyType.Legacy).ScriptPubKey)`
