### ISSUE TITLE
Gitbook edit caused direct commit to the master

### ISSUE THREAD

**Issue by hypergori** [ProgrammingBlockchain/ProgrammingBlockchain#45]
Sorry , I meant to create a pull request from Gitbook online for the first time.
but  it directly  committed and pushed the change and it went with lots of  escapes.
Let me create a roll back  pull request and another pull request .

**Comment by nopara73** [comment]
https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/pull/46#event-942489666
