### ISSUE TITLE
This sentence doesn't makes sense

### ISSUE THREAD

**Issue by wintercooled** [ProgrammingBlockchain/ProgrammingBlockchain#50]
(to me anyway) 

In Bitcoin transfer/Transaction section:

The relevant parts for now are the inputs and outputs. You can see that **out** 13.19683492 Bitcoin has been sent to a ScriptPubKey:

**Comment by nopara73** [comment]
Thanks, fixed it. Is it understandable now?  
https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/commit/3ac33010f48ff964cd1028968148e5ff300b7c59  
https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/commit/62c82fb21fabbf67f5a4f54cfa29267e290e4df1

**Comment by wintercooled** [comment]
yep!
