### ISSUE TITLE
FALSE: Console.WriteLine(samePrivateKey == privateKey); // True

### ISSUE THREAD

**Issue by andzsy** [ProgrammingBlockchain/ProgrammingBlockchain#51]
This line in https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/blob/master/bitcoin_transfer/private_key.md does not seem to work as indicated.

Try:

      Key privateKey = new Key();
      BitcoinSecret bitcoinSecret = privateKey.GetWif(Network.Main);
      Key samePrivateKey = bitcoinSecret.PrivateKey;
      Console.WriteLine(samePrivateKey == privateKey); // False !
      Console.WriteLine(samePrivateKey.ToString(Network.Main));
      Console.WriteLine(privateKey.ToString(Network.Main));

**Comment by nopara73** [comment]
That's no good. I opened an issue on NBitcoin: https://github.com/MetacoSA/NBitcoin/issues/252

**Comment by NicolasDorier** [comment]
indeed, I just fixed it
