### ISSUE TITLE
graphic typo

### ISSUE THREAD

**Issue by vnnkl** [ProgrammingBlockchain/ProgrammingBlockchain#64]
"Bob Private Key" rather than "Satoshi Private Key"
ProgrammingBlockchain/assets/bobSigned.png

used in L81 in ProgrammingBlockchain/other_types_of_ownership/multi_sig.md

**Comment by nopara73** [comment]
ACK

**Comment by andrasfuchs** [comment]
@nopara73 This was recently fixed (probably by you), could you close this issue?
