### ISSUE TITLE
About CombineSignatures()

### ISSUE THREAD

**Issue by youngmtool** [ProgrammingBlockchain/ProgrammingBlockchain#82]
At this page,
https://programmingblockchain.gitbooks.io/programmingblockchain/content/other_types_of_ownership/multi_sig.html

around this sentence, Then, with the TransactionBuilder, they create an unsigned transaction.

Alice signed unsigned transaction by her private key.
And then Bob signed the signed transaction by Alice by his private key.
And we additionally combined 2 transactions(one Alice signed, one Bob signed on the one Alice did.)

But is the third task(making fullySigned one) essentially need?
Or is there any particular situation which essentially needs 3rd task?
Because I saw bobSigned one and fullySigned one are identical.
It seems like 3rd task is needless.

**Comment by nopara73** [comment]
I'm a little occupied to play around with it, but I think you're right.  
I think if we'd do `.SignTransaction(unsigned);` instead of `.SignTransaction(aliceSigned);`, that'd be the correct case that fits to the explanation.  

Another question is, what you asked is if `CombineSignatures` could theoretically be left out in the case of `.SignTransaction(aliceSigned);`.

**Comment by youngmtool** [comment]
I think I understood the case CombineSignatures() is needed.
I tested like this.
```
Transaction aliceSigned =
    builder
        .AddCoins(coin)
        .AddKeys(alice)
        .SignTransaction(unsigned);
		
Transaction bobSigned =
    builder
        .AddCoins(coin)
        .AddKeys(bob)
        .SignTransaction(unsigned);
```
This is the way what the origianl source wrote.
But this one(.SignTransaction(unsigned)) is identical functionality to this one(.SignTransaction(aliceSigned)) because Alice has already manipulated unsigned transaction by signing her privateKey to Tx.

So I separated into each transaction like this.
```
TransactionBuilder builder = new TransactionBuilder();
TransactionBuilder builderForAlice = new TransactionBuilder();
TransactionBuilder builderForBob = new TransactionBuilder();

And I processed like this.
Transaction unsigned =
                builder
                    .AddCoins(coin)
                    .Send(nico, Money.Coins(1.0m))
                    .BuildTransaction(sign: false);

            
            Transaction aliceSigned =
                builderForAlice
                    .AddCoins(coin)
                    .AddKeys(alice)
                    .SignTransaction(unsigned);
            
            Transaction bobSigned =
                builderForBob
                    .AddCoins(coin)
                    .AddKeys(bob)
                    .SignTransaction(unsigned);

```					
In this case, this task is essentially needed.
```
Transaction fullySigned =
                builder
                    .AddCoins(coin)
                    .CombineSignatures(aliceSigned, bobSigned);
```
					
Do you think it's worth being appended to mention the need of CombineSignatures()?

And please merge what I did if there's no problem.
I don't know how to have multiple pull requests or whether it's possible or not.
My commits are appended to the existing PR, so it's getting bigger.

**Comment by nopara73** [comment]
> I don't know how to have multiple pull requests or whether it's possible or not.  

It is simple. Just edit this file here, on GitHub: https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/blob/master/other_types_of_ownership/multi_sig.md

**Comment by youngmtool** [comment]
Thank you for answer. But I meant Github multiple pull requests at the same time.
Because whenever I commit new changes, it would be appended to the exisiting pull request on Github which isn't yet merged. So, it's getting stacked and unmanageable.

**Comment by youngmtool** [comment]
Well, thinking again, you may have meant the my point. I'll try if it's working.

**Comment by nopara73** [comment]
For explanation, when you click edit, then you want to "save it", it'll automatically create a new branch, from this repository, commit there and make the PR here. It'll leave your forked branch you are working at intact.

**Comment by youngmtool** [comment]
Thanks for the help. But I'm sure if it's working well in the way you mentioned.

I edit some things on ProgrammingBlockchain/ProgrammingBlockchain, not on my forked one. And then, click "Propose file change". And returning back to my page, I can see added branches next to 671 commits, when I go into branches by clicking it, it gives me buttons such as "Change default branch", or "New pull request". Do I need to do something inside of them by clicking these buttons?

**Comment by nopara73** [comment]
It looks like you've figured it out already: https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/pull/89
