### ISSUE TITLE
One picture depiction looks wrong.

### ISSUE THREAD

**Issue by youngmtool** [ProgrammingBlockchain/ProgrammingBlockchain#83]
At this page, https://programmingblockchain.gitbooks.io/programmingblockchain/content/other_types_of_ownership/multi_sig.html.
Picture depiction above this sentence, Now, Bob and Alice can combine their signature into one transaction, looks wrong.
It looks like it should be Bob private key rather than Satoshi private key.

**Comment by nopara73** [comment]
Thanks, [fixed](https://github.com/ProgrammingBlockchain/ProgrammingBlockchain/blob/master/other_types_of_ownership/multi_sig.md).
