### ISSUE TITLE
Spend your coin: Example incorrectly tries to access property from the wrong object

### ISSUE THREAD

**Issue by varsnotwars** [ProgrammingBlockchain/ProgrammingBlockchain#96]
TxInAmount example incorrectly tries to access Amount from TxOut instead of from the ICoin object

`var txInAmount = receivedCoins[(int) outPointToSpend.N].TxOut.Amount;`

**Comment by nopara73** [comment]
Yes, it should've been either `coin.Amount` or `TxOut.Value`. Merged.
